### ISSUE TITLE
Accelerating mouse cursor

### ISSUE THREAD

**Issue by PrincessAkira** [PrincessAkira/Discord-Fixer#3]
Apparently, mouse cursor accelerates.
No idea. user reported.

**Comment by NULLYUKI** [comment]
The mouse cursor accelerates because "Discord-Fixer" is disabling the threads responsible for the **GetRawInputData** calls. 

Raw Input is used to get the direct input from the mouse. Disabling it causes Discord to receive the data from Windows which can results in slow or fast mouse movement depending on what mouse settings the user has set in Windows.

[GetRawInputData function (winuser.h)](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getrawinputdata)

**Comment by Aetopia** [comment]
> The mouse cursor accelerates because "Discord-Fixer" is disabling the threads responsible for the **GetRawInputData** calls.
> 
> Raw Input is used to get the direct input from the mouse. Disabling it causes Discord to receive the data from Windows which can results in slow or fast mouse movement depending on what mouse settings the user has set in Windows.
> 
> [GetRawInputData function (winuser.h)](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getrawinputdata)

This conclusion is entirely wrong. As the function's prefix states [**Get**RawInputData](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getrawinputdata), it simply obtains raw input data and its up to the application to decide how to react to this data essentially, disabling the thread that calls this function has nothing to do with mouse acceleration itself.

Please consider verifying that your mouse/Windows installation is not being the issue here.
